// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxOorFTKbF_-AkId_ggX6Lh8Rb45vZx0A',
    appId: '1:272110996309:web:1740931a99b90f8f77bddc',
    messagingSenderId: '272110996309',
    projectId: 'flutter-test-cc010',
    authDomain: 'flutter-test-cc010.firebaseapp.com',
    storageBucket: 'flutter-test-cc010.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVUj5FC8mJmGLm9ISpxbbeeCDxsDPBlfI',
    appId: '1:272110996309:android:461e7a1fa78be86477bddc',
    messagingSenderId: '272110996309',
    projectId: 'flutter-test-cc010',
    storageBucket: 'flutter-test-cc010.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTI5tnWwXcYgDs5zBwbV6R7JrHMFBSXVY',
    appId: '1:272110996309:ios:efee905de36a8d0277bddc',
    messagingSenderId: '272110996309',
    projectId: 'flutter-test-cc010',
    storageBucket: 'flutter-test-cc010.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTI5tnWwXcYgDs5zBwbV6R7JrHMFBSXVY',
    appId: '1:272110996309:ios:efee905de36a8d0277bddc',
    messagingSenderId: '272110996309',
    projectId: 'flutter-test-cc010',
    storageBucket: 'flutter-test-cc010.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
